  $(document).ready(function(){
   $('.img4').click(function(){
     $('.img4').animate({
		 width:'80%',
		 width:'60%',
		 width:'40%',
		 width:'20%',
		 width:'0%'
	 });
	  $('.img3').animate({
		 width:'20%',
		 width:'40%',
		 width:'60%',
		 width:'80%',
		 width:'100%'
	 });
   });
    
   $('.img3').click(function(){
     $('.img3').animate({
		 width:'80%',
		 width:'60%',
		 width:'40%',
		 width:'20%',
		 width:'0%'
	 });
     $('.img2').animate({
		 width:'20%',
		 width:'40%',
		 width:'60%',
		 width:'80%',
		 width:'100%'
	 });
   });
    $('.img2').click(function(){
     $('.img2').animate({
		 width:'80%',
		 width:'60%',
		 width:'40%',
		 width:'20%',
		 width:'0%'
	 });
     $('.img1').animate({
		 width:'20%',
		 width:'40%',
		 width:'60%',
		 width:'80%',
		 width:'100%'
	 });
   });
   $('.img1').click(function(){
     $('.img1').animate({
		 width:'80%',
		 width:'60%',
		 width:'40%',
		 width:'20%',
		 width:'0%'
	 });
     $('.img4').animate({
		 width:'20%',
		 width:'40%',
		 width:'60%',
		 width:'80%',
		 width:'100%'
	 });
   });
  });